#!/bin/bash

# Based on a script by a man named Andrew
# Originally located at http://blog.theinternets.be/rpi-munin-temperatures/

if [ "$1" == "autoconf" ]; then
     if [ -e /usr/local/bin/BMPPressure.py ]; then
         echo "yes"
     else
         echo "no"
         exit 1
     fi
elif [ "$1" == "config" ]; then
     echo "graph_title Luftdruck"
     echo "graph_args --base 1000 -X 0 --y-grid=10:1"
     echo "graph_scale no"
     echo "graph_vlabel Druck in hPa"
     echo "graph_category Umgebungswerte"
     echo "pressure.min 950"
     /usr/local/bin/rpi-sensors/GetSensorValuesSql.py -t pressure -c
else
     /usr/local/bin/rpi-sensors/GetSensorValuesSql.py -t pressure
fi
