#!/bin/bash

# Based on a script by a man named Andrew
# Originally located at http://blog.theinternets.be/rpi-munin-temperatures/

if [ "$1" == "autoconf" ]; then
     if [ -e /usr/local/bin/rpi-sensors/GetSensorValuesSql.py ]; then
         echo "yes"
     else
         echo "no"
         exit 1
     fi
elif [ "$1" == "config" ]; then
     echo "graph_title Temperatur"
     echo "graph_args --base 1000"
     echo "graph_vlabel Temperatur in Celsius"
     echo "graph_category Umgebungswerte"
     /usr/local/bin/rpi-sensors/GetSensorValuesSql.py -t temp -c
else
     /usr/local/bin/rpi-sensors/GetSensorValuesSql.py -t temp
fi
