#!/bin/bash

# Based on a script by a man named Andrew
# Originally located at http://blog.theinternets.be/rpi-munin-temperatures/

if [ "$1" == "autoconf" ]; then
     if [ -e "/usr/local/bin/rpi-sensors/GetSensorValuesSql.py" ]; then
         echo "yes"
     else
         echo "no"
         exit 1
     fi
elif [ "$1" == "config" ]; then
     echo "graph_title Luftfeuchtigkeit"
     echo "graph_args --base 1000 --lower-limit 0 --upper-limit 100"
     echo "graph_vlabel Feuchtigkeit"
     echo "graph_info Zeigt die Luftfeuchtigkeit in %1"
     echo "graph_category Umgebungswerte"
     echo "graph_scale no"
     /usr/local/bin/rpi-sensors/GetSensorValuesSql.py -t humid -c

else
     /usr/local/bin/rpi-sensors/GetSensorValuesSql.py -t humid
fi
