#!/bin/bash

# Based on a script by a man named Andrew
# Originally located at http://blog.theinternets.be/rpi-munin-temperatures/

if [ "$1" == "autoconf" ]; then
     if [ -e "/var/wde1/usb-wde1-last" ]; then
         echo "yes"
     else
         echo "no"
         exit 1
     fi
elif [ "$1" == "config" ]; then
     echo "graph_title Windgeschwindigkeit"
     echo "graph_args --base 1000"
     echo "graph_vlabel Wind"
     echo "graph_info Zeigt die Windgeschwindigkeit in km/h"
     echo "graph_category Umgebungswerte"
     echo "graph_scale no"
     /usr/local/bin/rpi-sensors/GetSensorValuesSql.py -t wind -c
else
    /usr/local/bin/rpi-sensors/GetSensorValuesSql.py -t wind
fi
